<?php

namespace JV\CoreBundle\Repository;

/**
 * BilletterieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletterieRepository extends \Doctrine\ORM\EntityRepository
{
}
