# src/JV/CoreBundle/Resources/config/routing.yml

jv_core_home:
    path:      /
    defaults: 
        _controller: JVCoreBundle:Billetterie:index

jv_core_reservation:
    path:      /reservation
    defaults: 
        _controller: JVCoreBundle:Billetterie:reservation

jv_core_coordonnees:
    path:      /coordonnees
    defaults: 
        _controller: JVCoreBundle:Billetterie:coordonnees

jv_core_recapitulatif:
    path:      /recapitulatif
    defaults: 
        _controller: JVCoreBundle:Billetterie:recapitulatif

jv_core_paiement:
    path:      /paiement
    defaults: 
        _controller: JVCoreBundle:Billetterie:paiement

jv_core_confirmation:
    path:      /confirmation
    defaults: 
        _controller: JVCoreBundle:Billetterie:confirmation